### ISSUE TITLE
Ender 3 model missing in Cura

### ISSUE THREAD

**Issue by namadori** [trouch/CreawsomeMod#106] opened 2019-08-30 19:46 UTC
I really liked the full Ender 3 model in the preview, I understand it was too big to be included for everyone. 
What about republishing the files with a quick guide on how to install them?

**Comment by jonnypage** [comment] 2019-09-17 22:31
I second this, I'd love to have the model in again

**Comment by natshi25** [comment] 2019-09-20 20:06
can i third this?

**Comment by adrianmihalko** [comment] 2019-09-28 11:45
Anyone?

**Comment by nallath** [comment] 2019-09-30 10:04
If someone puts in the effort to reduce the mesh so that it's not too big, it can be added again.

**Comment by trouch** [comment] 2020-03-21 23:30
duplicate of #112

**Closed by trouch** 2020-03-21 23:30 UTC
