### ISSUE TITLE
CreawsomeMod Beta 3 (Cura 4.1 Only) configuration error

### ISSUE THREAD

**Issue by 1aTa** [trouch/CreawsomeMod#56] opened 2019-05-29 20:24 UTC
Cura 4.0 removed along with all config files and clean install of Cura 4.1 + CreawesomeMod.

When duplicating Generic PLA I see the following error:

Your config appears to be corrupt. Something wrong with the following profiles: generic_pla_175_hms434_0.4mm_thermoplastic_extruder

**Comment by floxflux** [comment] 2019-05-29 21:09
me too!

**Comment by trouch** [comment] 2019-05-29 21:22
What OS ? Windows ? Haven't double checked on that one this one.
Just tested on macOS with another computer without issue.

**Comment by 1aTa** [comment] 2019-05-29 21:42
Windows 10 1903.

**Comment by Guilouz** [comment] 2019-05-29 23:57
Same here on macOS.
Error when duplicating duplicate generic material but still duplicated.
However, it is impossible to delete the duplicate material.

<img width="809" alt="Capture d’écran 2019-05-30 à 01 57 16" src="https://user-images.githubusercontent.com/12702322/58598874-4b295180-827e-11e9-84d4-e6eb9b07c379.png">

<img width="811" alt="Capture d’écran 2019-05-30 à 01 57 23" src="https://user-images.githubusercontent.com/12702322/58598886-511f3280-827e-11e9-8812-e246d244892d.png">

**Comment by 1aTa** [comment] 2019-05-30 01:06
It's not impossible, you just have to make a different material active.

You can't delete a material which is active and in use.

**Comment by trouch** [comment] 2019-05-30 07:41
I've been able to reproduce the error. Not sure about the root cause yet.

**Comment by trouch** [comment] 2019-05-30 08:26
Should be fixed with Beta 3.2.

**Comment by 1aTa** [comment] 2019-05-30 08:31
Great, thank you.

FYI typo CreawsomeM**i**d-Beta3.2-Cura4.1.zip

**Comment by trouch** [comment] 2019-05-30 08:36
> FYI typo CreawsomeM**i**d-Beta3.2-Cura4.1.zip
😬 fixed 🙈

**Closed by trouch** 2019-05-30 08:36 UTC
